### ISSUE TITLE
--debug-brk ?

### ISSUE THREAD

**Issue by paulirish** [jaridmargolin/inspect-process#16]
Does this work with debug-brk? I have been having some problems with it on a few scripts, but breaking before execution is a key usecase for me

**Comment by paulirish** [comment]
I see the note in the readme so i'll add a few more details

I have a few utility scripts that exit within a second. They aren't open long enough for me to set a breakpoint anywhere.

**Comment by jaridmargolin** [comment]
I try to handle debug-brk so the average user does not have to. It is however an oversight that I do not respect it in the case it is passed.

I will get a patch up shortly.

**Comment by jaridmargolin** [comment]
Patch available in v0.2.2

Appreciate you taking the time to file an issue. Need more people like you using it in order to iron out the obvious shortcomings :)
