### ISSUE TITLE
Doesn't work with the ava test runner

### ISSUE THREAD

**Issue by mightyiam** [jaridmargolin/inspect-process#20]
https://github.com/avajs/ava

I'm using `inspect ava --serial some-test-file.js`.

I've just tried debugging a trivial file as a sanity check and it worked.

Perhaps ava is using child processes with the `--serial` option, as well...

**Comment by jaridmargolin** [comment]
After a quick review, looks like ava is using fork under the hood. There is a small chance it is possible to support child process, but its fairly hacky (see #5).

Thanks for the report.

**Comment by mightyiam** [comment]
Perhaps it could be ava's job to provide an API for debugging child processes.

**Comment by mightyiam** [comment]
But why stop there? Perhaps node could provide such an API.

**Comment by jaridmargolin** [comment]
Hmmm.. I don't see a clear path for ava to provide an API for this. Possibly at a lower level node would be able to expose easier hooks, but its not really clear to me.

I am going to close this particular issue. If you want to follow any progress **inspect-process** is capable of making, see #5.

**Comment by gillesdemey** [comment]
FWIW it works fine with AVA when running it via the profile file (and it should work with the `--serial` flag too)

`inspect node_modules/ava/profile.js test-file.js`

**Comment by mightyiam** [comment]
Yup. I wrote the page:
https://github.com/avajs/ava/blob/master/docs/recipes/debugging-with-chrome-devtools.md

**Comment by jaridmargolin** [comment]
Thanks @gillesdemey @mightyiam!
