### ISSUE TITLE
Node 8.1.3?

### ISSUE THREAD

**Issue by fullofcaffeine** [jaridmargolin/inspect-process#52]
Looks like the protocol changed in `8.1.3`? Now `--inspect` only prints a `ws://` URL, and `inspect-process` fails. It looks like `--inspect` now automatically opens the debug tab for you, but it doesn't seem to work well - i.e it fails for me when using with `ava`, it hangs there forever.

Maybe I should downgrade?

**Comment by jaridmargolin** [comment]
@fullofcaffeine - I unfortunately have very little time to spend on `inspect-process` right now :/ Maybe in the coming weeks I will be able to set aside some time, but I definitely 
don't want to make any promises.
