### ISSUE TITLE
Feature request: Breakpoint automatically when an error occurred

### ISSUE THREAD

**Issue by Josema** [jaridmargolin/inspect-process#7]
I love this project much more than node-inspector node-nightly or any other. But for me to be perfect it would be that the debugger takes a breakpoint automatically just before the script crash. On the line of the crash. But not sure if this feature is possible.

**Comment by jaridmargolin** [comment]
Seems plausible. I might be completely oversimplifying the issue, but I believe I could just inject a module that listens to uncaughtExceptions on the process:

```
process.on('uncaughtException', function (err) {
  debugger;
})
```

It would need to live behind a flag (I'm thinking maybe `--debug-uncaught`?). Will be dependent on completion of #2

**Comment by Josema** [comment]
It's already available?

I just updated and tried `inspect test/test.js --debug-uncaugh` but does not work.

```
ReferenceError: myfun is not defined
    at Object.<anonymous> (/Users/enzo/
```

**Comment by jaridmargolin** [comment]
It's is behind the flag --debug-exception. Moving forward you can use inspect --help to see all available options.
